# !!!!!! You need to rename this file to secrets.toml and add username and passcode below !!!!!!

# Credentials for WebDAV file storage such as SwitchDrive
[webdav]
base_url = "https://drive.switch.ch/remote.php/webdav/"
username = "joyce.baumann04@gmail.com"
password = "KPCDA-AWSUV-EOVPN-MLCOO"


